
# === Policy configurations ===
policy_checkpoint_path: "checkpoints/policy_biped.onnx"

# === Networking configurations ===
ip_robot_addr: "127.0.0.1"
ip_policy_obs_port: 10000
ip_host_addr: "127.0.0.1"
ip_policy_acs_port: 10001

# === Physics configurations ===
control_dt: 0.004   # 250 Hz
policy_dt: 0.04      # 25 Hz
physics_dt: 0.001    # 1000 Hz
cutoff_freq: 200.0

# === Articulation configurations ===
num_joints: 12
joint_kp: 20
joint_kd: 2
effort_limits: 7.5
default_base_position: [0.0, 0.0, 0.0]
default_joint_positions: [0.0, 0.0, -0.2, 0.4, -0.3, 0.0, 0.0, 0.0, -0.2, 0.4, -0.3, 0.0]

# === Observation configurations ===
num_observations: 45
history_length: 0

# === Command configurations ===
command_velocity: [0.0, 0.0, 0.0]

# === Action configurations ===
num_actions: 12
action_indices:
- 0
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10
- 11
action_scale: 0.25
action_limit_lower: -200
action_limit_upper: 200
